on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Create release
      - name: Create release
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `GH_TOKEN` (this secret name is not important).
          token: ${{ secrets.GH_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json
      
      # Checkout
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9.13.2
          run_install: false

      # Install Node.js
      - name: Setup Node.js environment
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      # Get pnpm store directory
      - name: Get pnpm store directory
        if: ${{ steps.release.outputs.release_created }}
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Setup pnpm cache
      - name: Setup pnpm cache
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install

      # Prepare new version
      # https://github.com/google-github-actions/release-please-action#outputs
      - name: Prepare new version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pnpm prepareRelease

      # Build for production
      - name: Build for production
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      # Archive package
      - name: Archive package
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm package

      # Upload package to release
      # https://github.com/philips-labs/terraform-aws-github-runner/blob/main/.github/workflows/release.yml#L46
      - name: Upload package.zip to the release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls -l ./build
          for f in $(find ./build -name '*.zip'); do
            gh release upload ${{ steps.release.outputs.tag_name }} $f
          done
